version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@surge/token-lists'
      - dependency-name: '@surge/redux-multicall'
    reviewers:
      - 'Surge/dependabot-reviewers'
